version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
