# Site settings
title: Matthew Brown
email: me@matthewbrown.io
author: Matthew Brown
description: "Matthew Brown: Building Maxwell MRI"
baseurl: ""
url: "http://matthewbrown.io"
google_analytics: UA-43429204-1

twitter_username: mnbbrown
github_username: mnbbrown
linkedin_username: mnbbrown

# Build settings
permalink: /:year/:month/:day/:title/
sass:
  compressed: true

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  - others

plugins:
  - jekyll-sitemap
