# Site settings
title: Matthew Brown
email: me@matthewbrown.io
author: Matthew Brown
description: "Matthew Brown: Developer and Consultant"
baseurl: ""
url: "http://matthewbrown.io"
google_analytics: UA-43429204-1

twitter_username: mnbbrown
github_username: mnbbrown
linkedin_username: mnbbrown

# Build settings
markdown: redcarpet
permalink: pretty
sass:
  compressed: true

gems:
  - jekyll-sitemap
