# Site settings
title: Getting There Is Half The Fun
email: me@matthewbrown.io
author: Matthew Brown
description: "The blog of Matthew Brown: IT consultant, entreprenuer, business student"
baseurl: ""
url: "http://matthewbrown.io"
google_analytics:
animated: true
show_related_posts: false

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

gems:
  - jekyll-sitemap