# Site settings
title: Getting There Is Half The Fun
email: me@matthewbrown.io
author: Matthew Brown
description: "The blog of Matthew Brown: IT consultant, entreprenuer, business student"
baseurl: ""
url: "/"
google_analytics:
animated: true
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass:
  compressed: true

gems:
  - jekyll-sitemap
  - typhoeus
  - shellwords
  - nokogiri

flickr:
     api_key: f2734c60165da790ea5e62c6ea013dee